//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Argument) DeepCopyInto(out *Argument) {
	*out = *in
	out.XMLName = in.XMLName
	in.CollectionProp.DeepCopyInto(&out.CollectionProp)
	out.StringProp = in.StringProp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Argument.
func (in *Argument) DeepCopy() *Argument {
	if in == nil {
		return nil
	}
	out := new(Argument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoolProp) DeepCopyInto(out *BoolProp) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoolProp.
func (in *BoolProp) DeepCopy() *BoolProp {
	if in == nil {
		return nil
	}
	out := new(BoolProp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionProp) DeepCopyInto(out *CollectionProp) {
	*out = *in
	out.XMLName = in.XMLName
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]Argument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionProp.
func (in *CollectionProp) DeepCopy() *CollectionProp {
	if in == nil {
		return nil
	}
	out := new(CollectionProp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElementProp) DeepCopyInto(out *ElementProp) {
	*out = *in
	out.XMLName = in.XMLName
	in.CollectionProp.DeepCopyInto(&out.CollectionProp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElementProp.
func (in *ElementProp) DeepCopy() *ElementProp {
	if in == nil {
		return nil
	}
	out := new(ElementProp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowArgs) DeepCopyInto(out *FlowArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowArgs.
func (in *FlowArgs) DeepCopy() *FlowArgs {
	if in == nil {
		return nil
	}
	out := new(FlowArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPArgument) DeepCopyInto(out *HTTPArgument) {
	*out = *in
	out.XMLName = in.XMLName
	if in.StringProps != nil {
		in, out := &in.StringProps, &out.StringProps
		*out = make([]StringProp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPArgument.
func (in *HTTPArgument) DeepCopy() *HTTPArgument {
	if in == nil {
		return nil
	}
	out := new(HTTPArgument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSamplerProxy) DeepCopyInto(out *HTTPSamplerProxy) {
	*out = *in
	out.XMLName = in.XMLName
	if in.BoolProps != nil {
		in, out := &in.BoolProps, &out.BoolProps
		*out = make([]BoolProp, len(*in))
		copy(*out, *in)
	}
	in.ElementProp.DeepCopyInto(&out.ElementProp)
	if in.StringProps != nil {
		in, out := &in.StringProps, &out.StringProps
		*out = make([]StringProp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSamplerProxy.
func (in *HTTPSamplerProxy) DeepCopy() *HTTPSamplerProxy {
	if in == nil {
		return nil
	}
	out := new(HTTPSamplerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashTree) DeepCopyInto(out *HashTree) {
	*out = *in
	out.XMLName = in.XMLName
	in.TestPlan.DeepCopyInto(&out.TestPlan)
	in.ThreadGroup.DeepCopyInto(&out.ThreadGroup)
	in.HeaderManager.DeepCopyInto(&out.HeaderManager)
	in.HTTPSamplerProxy.DeepCopyInto(&out.HTTPSamplerProxy)
	if in.HashTree != nil {
		in, out := &in.HashTree, &out.HashTree
		*out = new(HashTree)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashTree.
func (in *HashTree) DeepCopy() *HashTree {
	if in == nil {
		return nil
	}
	out := new(HashTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
	out.XMLName = in.XMLName
	if in.StringProps != nil {
		in, out := &in.StringProps, &out.StringProps
		*out = make([]StringProp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderManager) DeepCopyInto(out *HeaderManager) {
	*out = *in
	out.XMLName = in.XMLName
	in.CollectionProp.DeepCopyInto(&out.CollectionProp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderManager.
func (in *HeaderManager) DeepCopy() *HeaderManager {
	if in == nil {
		return nil
	}
	out := new(HeaderManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JMeterTestPlan) DeepCopyInto(out *JMeterTestPlan) {
	*out = *in
	out.XMLName = in.XMLName
	in.HashTree.DeepCopyInto(&out.HashTree)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JMeterTestPlan.
func (in *JMeterTestPlan) DeepCopy() *JMeterTestPlan {
	if in == nil {
		return nil
	}
	out := new(JMeterTestPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTest) DeepCopyInto(out *LoadTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTest.
func (in *LoadTest) DeepCopy() *LoadTest {
	if in == nil {
		return nil
	}
	out := new(LoadTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestList) DeepCopyInto(out *LoadTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestList.
func (in *LoadTestList) DeepCopy() *LoadTestList {
	if in == nil {
		return nil
	}
	out := new(LoadTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestSpec) DeepCopyInto(out *LoadTestSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]FlowArgs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestSpec.
func (in *LoadTestSpec) DeepCopy() *LoadTestSpec {
	if in == nil {
		return nil
	}
	out := new(LoadTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestStatus) DeepCopyInto(out *LoadTestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestStatus.
func (in *LoadTestStatus) DeepCopy() *LoadTestStatus {
	if in == nil {
		return nil
	}
	out := new(LoadTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringProp) DeepCopyInto(out *StringProp) {
	*out = *in
	out.XMLName = in.XMLName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringProp.
func (in *StringProp) DeepCopy() *StringProp {
	if in == nil {
		return nil
	}
	out := new(StringProp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPlan) DeepCopyInto(out *TestPlan) {
	*out = *in
	out.XMLName = in.XMLName
	in.ElementProp.DeepCopyInto(&out.ElementProp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPlan.
func (in *TestPlan) DeepCopy() *TestPlan {
	if in == nil {
		return nil
	}
	out := new(TestPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreadGroup) DeepCopyInto(out *ThreadGroup) {
	*out = *in
	out.XMLName = in.XMLName
	in.ElementProp.DeepCopyInto(&out.ElementProp)
	if in.StringProps != nil {
		in, out := &in.StringProps, &out.StringProps
		*out = make([]StringProp, len(*in))
		copy(*out, *in)
	}
	if in.BoolProps != nil {
		in, out := &in.BoolProps, &out.BoolProps
		*out = make([]BoolProp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreadGroup.
func (in *ThreadGroup) DeepCopy() *ThreadGroup {
	if in == nil {
		return nil
	}
	out := new(ThreadGroup)
	in.DeepCopyInto(out)
	return out
}
