//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2022-2023 Chaos Meta Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConfig) DeepCopyInto(out *CloudConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConfig.
func (in *CloudConfig) DeepCopy() *CloudConfig {
	if in == nil {
		return nil
	}
	out := new(CloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdasOption) DeepCopyInto(out *EdasOption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdasOption.
func (in *EdasOption) DeepCopy() *EdasOption {
	if in == nil {
		return nil
	}
	out := new(EdasOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmetaCluster) DeepCopyInto(out *ChaosmetaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmetaCluster.
func (in *ChaosmetaCluster) DeepCopy() *ChaosmetaCluster {
	if in == nil {
		return nil
	}
	out := new(ChaosmetaCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosmetaCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmetaClusterList) DeepCopyInto(out *ChaosmetaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosmetaCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmetaClusterList.
func (in *ChaosmetaClusterList) DeepCopy() *ChaosmetaClusterList {
	if in == nil {
		return nil
	}
	out := new(ChaosmetaClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosmetaClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmetaClusterSpec) DeepCopyInto(out *ChaosmetaClusterSpec) {
	*out = *in
	if in.KubernetesOption != nil {
		in, out := &in.KubernetesOption, &out.KubernetesOption
		*out = new(KubernetesOption)
		**out = **in
	}
	if in.MonitorOption != nil {
		in, out := &in.MonitorOption, &out.MonitorOption
		*out = new(MonitorOption)
		**out = **in
	}
	if in.EdasOption != nil {
		in, out := &in.EdasOption, &out.EdasOption
		*out = new(EdasOption)
		**out = **in
	}
	out.CloudOption = in.CloudOption
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmetaClusterSpec.
func (in *ChaosmetaClusterSpec) DeepCopy() *ChaosmetaClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosmetaClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmetaClusterStatus) DeepCopyInto(out *ChaosmetaClusterStatus) {
	*out = *in
	in.LastUpdatedTimestamp.DeepCopyInto(&out.LastUpdatedTimestamp)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmetaClusterStatus.
func (in *ChaosmetaClusterStatus) DeepCopy() *ChaosmetaClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosmetaClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOption) DeepCopyInto(out *KubernetesOption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOption.
func (in *KubernetesOption) DeepCopy() *KubernetesOption {
	if in == nil {
		return nil
	}
	out := new(KubernetesOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorOption) DeepCopyInto(out *MonitorOption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorOption.
func (in *MonitorOption) DeepCopy() *MonitorOption {
	if in == nil {
		return nil
	}
	out := new(MonitorOption)
	in.DeepCopyInto(out)
	return out
}
