
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: chaosmeta-inject-operator
  name: chaosmeta-inject-controller-manager
  namespace: chaosmeta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: chaosmeta-inject-operator
  name: chaosmeta-inject-leader-election-role
  namespace: chaosmeta
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: chaosmeta-inject-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - deployments/scale
  - statefulsets/scale
  - replicasets/scale
  verbs:
  - '*'
- apiGroups:
  - batchs
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - chaosmeta.io
  resources:
  - experiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaosmeta.io
  resources:
  - experiments/finalizers
  verbs:
  - update
- apiGroups:
  - chaosmeta.io
  resources:
  - experiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  - pods/exec
  - services
  verbs:
  - '*'
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - '*'
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests
  verbs:
    - '*'
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests/status
    - certificatesigningrequests/approval
  verbs:
    - update
- apiGroups:
    - certificates.k8s.io
  resources:
    - signers
  resourceNames:
    - kubernetes.io/kubelet-serving # example.com/* 可用于为 “example.com” 域中的所有签名者授权
  verbs:
    - sign
    - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: chaosmeta-inject-operator
  name: chaosmeta-inject-leader-election-rolebinding
  namespace: chaosmeta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosmeta-inject-leader-election-role
subjects:
- kind: ServiceAccount
  name: chaosmeta-inject-controller-manager
  namespace: chaosmeta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: chaosmeta-inject-operator
  name: chaosmeta-inject-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaosmeta-inject-manager-role
subjects:
- kind: ServiceAccount
  name: chaosmeta-inject-controller-manager
  namespace: chaosmeta
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: chaosmeta-inject-operator
  name: chaosmeta-inject-webhook-service
  namespace: chaosmeta
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
    app: chaosmeta-inject
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: chaosmeta-inject-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: chaosmeta-inject-operator
    control-plane: controller-manager
  name: chaosmeta-inject-controller-manager
  namespace: chaosmeta
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app: chaosmeta-inject
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app: chaosmeta-inject
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: registry.cn-hangzhou.aliyuncs.com/chaosmeta/chaosmeta-inject-controller:v0.1.2
        imagePullPolicy: Always
        env:
          - name: DEFAULTNAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 3
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /config/chaosmeta-inject.json
          name: config-volume
          subPath: chaosmeta-inject.json
      securityContext:
        runAsNonRoot: true
      serviceAccountName: chaosmeta-inject-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: chaosmeta-inject-config
        name: config-volume
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: chaosmeta-inject-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: chaosmeta-inject-webhook-service
      namespace: chaosmeta
      path: /mutate-chaosmeta-io-v1alpha1-experiment
  failurePolicy: Fail
  name: mexperiment.kb.io
  rules:
  - apiGroups:
    - chaosmeta.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - experiments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: chaosmeta-inject-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: chaosmeta-inject-webhook-service
      namespace: chaosmeta
      path: /validate-chaosmeta-io-v1alpha1-experiment
  failurePolicy: Fail
  name: vexperiment.kb.io
  rules:
  - apiGroups:
    - chaosmeta.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - experiments
  sideEffects: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosmeta-inject-config
  namespace: chaosmeta
data:
  chaosmeta-inject.json: |-
    {
      "worker": {
        "poolCount": 16
      },
      "ticker": {
        "autoCheckInterval": 2
      },
      "executor": {
        "mode": "daemonset",
        "executor": "chaosmetad",
        "version": "0.5.1",
        "agentConfig": {
          "agentPort": 29595
        },
        "daemonsetConfig": {
          "localExecPath": "/tmp",
          "daemonNs": "chaosmeta",
          "daemonLabel": {
            "app.chaosmeta.io": "chaosmeta-daemon"
          }
        }
      }
    }
